name: Build and Upload Executable

on:
  push:
    branches:
      - main  # 或者是你的默认分支

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - uses: actions/checkout@v3  # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # 指定 Go 版本

      - name: Copy and Execute Script
        run: |
          bash run.sh  # 执行脚本

      - name: commit and push
        run: |
          git add .
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "Automated build and upload executable"
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # 设置 Docker Buildx
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 # 登录到 Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 通过 Secrets 存储 Docker 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 通过 Secrets 存储 Docker 密码

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2 # 构建和推送 Docker 镜像
        with:
          context: . # Dockerfile 和其他构建文件所在的目录
          file: ./Dockerfile # Dockerfile 的路径
          push: true
          tags: summerkK/gpt3.5-api:latest
