name: Build and Upload Executable

on:
  push:
    branches:
      - main  # 或者是你的默认分支

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - uses: actions/checkout@v3  # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # 指定 Go 版本

      - name: Copy and Execute Script
        run: |
          bash run.sh  # 执行脚本

      - name: commit and push
        run: |
          git add .
          git config --global user.name 'workflow'
          git config --global user.email 'workflow@users.noreply.github.com'
          git commit -am "Automated build and upload executable"
          git push